[package]
name = "ignition"
version = "0.1.0"
edition = "2024"

[dependencies]
indexify = { path = "../crates/indexify" }
vaultify = { path = "../crates/vaultify" }
logger = { path = "../crates/logger" }
