stages:
  - build

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo/
    - target/

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

build:
  stage: build
  image: rust:latest
  script:
    - cargo build --release --verbose
  artifacts:
    paths:
      - target/release/
  only:
    - main