[package]
name = "indexify"
version = "0.1.0"
edition = "2024"

[dependencies]
tantivy = "0.24.1"
jwalk = "0.8.1"
once_cell = "1.21.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

vaultify = { path = "../vaultify" }
