name: ci

on:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo install cargo-bundle
      - run: cargo install apple-codesign
      - run: brew install create-dmg

      - name: Build and Bundle
        run: cargo bundle --release

      - name: Apple Code Signing for APP
        run: echo "${{ secrets.P12_FILE_BASE64 }}" | base64 -d > certificate.p12
      - uses: indygreg/apple-code-sign-action@v1
        with:
          input_path: target/release/bundle/osx/Anything.app
          output_path: build/Anything.app
          p12_file: certificate.p12
          p12_password: ${{ secrets.P12_PASSWORD }}

      - name: Create DMG
        run: |
          create-dmg \
            --volname "${{ vars.APP_NAME }}" \
            --background "assets/images/dmg-background.png" \
            --window-size 660 400 \
            --icon-size 120 \
            --icon "Anything.app" 180 170 \
            --hide-extension "${{ vars.APP_NAME }}.app" \
            --app-drop-link 480 170 \
            "${{ vars.APP_NAME }}.dmg" \
            "build"

          mv "${{ vars.APP_NAME }}.dmg" build/

      - name: Apple Code Signing for DMG
        uses: indygreg/apple-code-sign-action@v1
        with:
          input_path: build/${{ vars.APP_NAME }}.dmg
          output_path: build/${{ vars.APP_NAME }}-aarch64.dmg
          p12_file: certificate.p12
          p12_password: ${{ secrets.P12_PASSWORD }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/${{ vars.APP_NAME }}-aarch64.dmg
